### ISSUE TITLE
Error in gridPLT() : Figure region too small and/or viewport too large

### ISSUE THREAD

**Issue by PromoterBio-zhaojp** [YuLab-SMU/ChIPseeker#102]
Y叔您好，我在用ChIPseeker的upsetplot时，只要upsetplot(peakAnno, vennpie=TRUE)进行这个操作，就会报错，我输出到pdf文件也不可以，想问一下怎么解决？

**Comment by GuangchuangYu** [comment]
我重新写了upsetplot，你装github版本，这个问题就不存在了。
