### ISSUE TITLE
Number of peaks is wrong

### ISSUE THREAD

**Issue by haowenz** [YuLab-SMU/ChIPseeker#105]
Hi,

There are 10812 peaks in the file. But ChIPseeker only loads 18011 peaks. Can you have a look at this issue?

Thanks,
Haowen Zhang

[ENCODE_peaks.narrowPeak.zip](https://github.com/YuLab-SMU/ChIPseeker/files/3736480/ENCODE_peaks.narrowPeak.zip)

**Comment by haowenz** [comment]
```
$ENCODE
Annotated peaks generated by ChIPseeker
10808/10811  peaks were annotated
Genomic Annotation Summary:
             Feature  Frequency
9           Promoter 68.6806070
4             5' UTR  0.1850481
3             3' UTR  1.1565507
1           1st Exon  1.2768320
7         Other Exon  1.3971132
2         1st Intron  5.6624722
8       Other Intron  8.6047372
6 Downstream (<=300)  0.5921540
5  Distal Intergenic 12.4444856
```

BTW, This is what I got after annotation.

**Comment by GuangchuangYu** [comment]
reproducible code pls?

**Comment by haowenz** [comment]
```
library(ChIPseeker)
library(clusterProfiler)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)

peak_files <- list.files("/hwzhang/tmp/peak", pattern= ".narrowPeak", full.names=T)
names(peak_files) <- c("ENCODE")

gene_txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
peak_gene_anno_list <- lapply(peak_files, annotatePeak, TxDb=gene_txdb, tssRegion=c(-1000, 1000), verbose=FALSE)
peak_gene_anno_list
```

Of course in my case, I decompressed the peak file and put it into "/hwzhang/tmp/peak". I also tried some other peak files and got the same result, that is losing one peak. I guess there might be bugs when loading the peak file.

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/ChIPseeker/blob/master/R/getNearestFeatureIndicesAndDistances.R#L156-L160>.

**Comment by GuangchuangYu** [comment]
If ChIPseeker cannot find annotation for the peak, it will be filter out.

**Comment by haowenz** [comment]
What about vennplot.peakfile? You can try the following code with the attached peak files.

```
library(ChIPseeker)
library(clusterProfiler)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)

peak_files <- list.files("/hwzhang/tmp/peak", pattern= ".narrowPeak", full.names=T)
names(peak_files) <- c("1", "2")

gene_txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

pdf("/hwzhang/tmp/test.pdf")
vennplot.peakfile(peak_files,c("1", "2"))
dev.off()
```

The Venn plot is also attached. And the number of peaks again is wrong again in the plots. 

[peaks.zip](https://github.com/YuLab-SMU/ChIPseeker/files/3741905/peaks.zip)
[test.pdf](https://github.com/YuLab-SMU/ChIPseeker/files/3741904/test.pdf)
