### ISSUE TITLE
Expose option for multicore CPUs

### ISSUE THREAD

**Issue by msmallegan** [YuLab-SMU/ChIPseeker#110]
Hi,

When using `plotAvgProf`, we were surprised to see that some component was using all the CPUs on our machine. We tried adding `ncpus` and `mc.cores` as named arguments to `plotAvgProf`, but this didn't limit the number of cores. Using all cores is fine when you're running locally, but in a shared compute environment is unacceptable. Would you be able to add the number of cores to use as an option when running this command?

Here is a link to the line I'm referring to:
https://github.com/YuLab-SMU/ChIPseeker/blob/7596f0fb9897026229933c06fdecc9c509770d8d/R/utilities.R#L107

Thanks,
Michael

**Comment by GuangchuangYu** [comment]
solved.
