### ISSUE TITLE
options(ChIPseeker.downstreamDistance = 500) seems not work

### ISSUE THREAD

**Issue by shangguandong1996** [YuLab-SMU/ChIPseeker#112]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/chipseeker/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/chipseeker/documentation/) This document is 404, I read the Bioconductor
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

```{r}
library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene

files <- getSampleFiles()

options(ChIPseeker.downstreamDistance = 1000)
peakAnno <- annotatePeak(files[[4]], tssRegion=c(-3000, 3000),
                         TxDb=txdb)
plotAnnoPie(peakAnno)

options(ChIPseeker.downstreamDistance = 10)
peakAnno <- annotatePeak(files[[4]], tssRegion=c(-3000, 3000),
                         TxDb=txdb)
plotAnnoPie(peakAnno)

```

I find that no matter what number I enter in options(ChIPseeker.downstreamDistance = ). The percent of downstream is same, But the number in plot indeed change.

![图片](https://user-images.githubusercontent.com/22555126/74704673-35185280-524c-11ea-8575-cf46a896f1ac.png)
![图片](https://user-images.githubusercontent.com/22555126/74704679-3ba6ca00-524c-11ea-8126-a5f7b21173d2.png)
And I also attached the Rmd

[ChIPSeeker_issue.zip](https://github.com/YuLab-SMU/ChIPseeker/files/4217364/ChIPSeeker_issue.zip)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `ChIPseeker`

I also post a Q in Bioconductor
https://support.bioconductor.org/p/128398/

**Comment by MingLi-929** [comment]
The marker of the picture above come from `getGenomicAnnoStat()`.
https://github.com/YuLab-SMU/ChIPseeker/blob/d1ca24742edabf0e9b08711244bcb6ec01dd11f5/R/plotAnno.R#L191-L208
as it show above the `getGenomicAnnoStat()` will classify the gene with "downstream" into "Downstream(<N)". The N is decided by options(ChIPseeker.downstreamDistance = 500).

but in `getGenomicAnnotation()` 
https://github.com/YuLab-SMU/ChIPseeker/blob/d1ca24742edabf0e9b08711244bcb6ec01dd11f5/R/getGenomicAnnotation.R#L169-L180
it will only give "downstream" to invariable amount of gene(0-3k).

So no matter no matter how you change the options(ChIPseeker.downstreamDistance = N), it will not chang the ratio of "Downstream(<N)"
