### ISSUE TITLE
对于注释结果的疑问

### ISSUE THREAD

**Issue by axin527** [YuLab-SMU/ChIPseeker#124]
### Prerequisites

+ [√ ] Have you read [Feedback](https://guangchuangyu.github.io/chipseeker/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [√ ] make sure your are using the latest release version

clusterProfiler v3.14.3
ChIPseeker v1.22.1

	* [√ ] read the [documents](https://guangchuangyu.github.io/chipseeker/documentation/)
	* [√ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

**已经阅读过说明文档以及发表的论文，但是我的问题没有找到答案，希望得到您的解答。**
以下是我的脚本，只想对peak进行位置注释。
#!/bin/env Rscript
args<-commandArgs(T)
# 载入各种包
library(ChIPseeker)
library(clusterProfiler)
library(GenomicFeatures)
# 生成TxDb文件
txdb <- makeTxDbFromGFF(file = args[1])
# 读入peak文件
peak <- readPeakFile(args[2])
# Peak Annotation
peakAnno <- annotatePeak(peak, tssRegion=c(-2000, 2000), TxDb=txdb, verbose=FALSE)
# 保存文件
write.table(as.data.frame(peakAnno),file=args[3],sep='\t',quote = F,row.names=FALSE,col.names=TRUE)

**以下是部分的注释结果：
seqnames        start   end     width   strand  V4      annotation      geneChr geneStart       geneEnd geneLength      geneStrand      geneId  transcriptId    distanceToTSS
chr01   54179   55190   1012    *       ATAC_BG_TZ_10_210       Promoter (<=1kb)        4       54019   68058   14040   1       Lsi01G000020    Lsi01G000020.1  160
chr01   385152  385451  300     *       ATAC_BG_TZ_10_220       Promoter (<=1kb)        4       375882  385700  9819    2       Lsi01G000340    Lsi01G000340.1  249

**因为注释是按照Promoter，5’ UTR，3’ UTR，Exon，Intron，Downstream，Intergenic的优先级顺序进行的，所以只要是和Promoter有overlap的就注释为Promoter。但是上面第一个例子：peak区域位于基因内部，但是注释出来是Promoter区域。而且遇到好几处都是这样，请问这是哪里出的问题？
主要是不理解tssRegion = c(-2000, 2000) 【tssRegion Region Range of TSS】的作用，希望得到您的解答。

### Ask in right place

* [√ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `ChIPseeker`

**Comment by qliugithub** [comment]
我来回答一下吧，我之前也有这个迷惑，`tssRegion = c(-2000, 2000) ` 表示定义 Promoter 的范围，也就是说只要你的 Peak 与 TSS 上下游 2kb 有交际那么就会被注释为启动子区。哪怕是你这个 Peak 是位于你的最邻近的基因的下游。。希望能解答你的疑惑
![image](https://user-images.githubusercontent.com/22570997/84466486-12eb8a00-acac-11ea-9b90-6d7d9e8b2269.png)
