### ISSUE TITLE
covplot from ChIPSeeker gives distribution of abundant chromosomes.

### ISSUE THREAD

**Issue by ahua217** [YuLab-SMU/ChIPseeker#133]
> I have some bed files from CUT & RUN analysis by SEACR. Now I use ChIPseeker to plot the chromosome distribution of peaks. This is what I entered:

library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(clusterProfiler)
library(org.Hs.eg.db)
peak <-readPeakFile("/Users/AAData/stringent.bed")
peak
>GRanges object with 23530 ranges and 3 metadata columns:
          seqnames            ranges strand |        V4        V5                     V6
             <Rle>         <IRanges>  <Rle> | <numeric> <numeric>               <factor>
      [1]     chr1       10128-10532      * |   8748.63   43.6341       chr1:10292-10414
      [2]     chr1       19087-19758      * |   9414.04   32.7256       chr1:19514-19522
      [3]     chr1     228294-228653      * |   7515.96   32.7256     chr1:228420-228556
      [4]     chr1     230971-231510      * |   11573.9   43.6341     chr1:231129-231131
      [5]     chr1     259534-260085      * |   7668.68   32.7256     chr1:259753-259761
      ...      ...               ...    ... .       ...       ...                    ...
  [23526]     chrY 13869691-13869895      * |   7385.06   65.4511 chrY:13869771-13869844
  [23527]     chrY 28797432-28798089      * |   7254.15    21.817 chrY:28798040-28798047
  [23528]     chrY 58992162-58992530      * |   7428.69   54.5426 chrY:58992403-58992415
  [23529]     chrY 58994709-58995034      * |   9119.52   54.5426 chrY:58994907-58994939
  [23530]     chrY 59016879-59017391      * |   9948.56   32.7256 chrY:59016905-59017061
  -------

covplot(peak, weightCol="V5")

The plot turned out to be what I need as well as some extra chromosomes with few peaks. Any clue on how to remove those extra ones?

Thank you very much!

![image](https://user-images.githubusercontent.com/71511628/93609589-0ad17380-f99a-11ea-8904-1e39c91c24be.png)

> ### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/chipseeker/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/chipseeker/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `ChIPseeker`

**Comment by ahua217** [comment]
I found it was solved if I forced the setting of chromosomes, though I still do not know where those previous "blank" chromosomes were from.

>covplot(peak, weightCol="V5", chrs=c("chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22","chrX"))

**Comment by xj7757417771** [comment]
我在使用ChIPseeker的时候，遇到了如下问题：
New names:
* chr -> chr...2
* start -> start...3
* end -> end...4
* value -> value...5
* chr -> chr...6
* ...
New names:
* chr -> chr...2
* start -> start...3
* end -> end...4
* value -> value...5
* chr -> chr...6
* ...
错误: Assigned data `factor(tm$chr, levels = chr.sorted)` must be compatible with existing data.
x Existing data has 2994 rows.
x Assigned data has 0 rows.
i Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
此外: Warning message:
Unknown or uninitialised column: `chr`. 
covplot(files[[4]])这个命令是可以正常画图的。请问这个是什么原因造成的呢？

**Comment by GuangchuangYu** [comment]
should be fixed in github version.
