### ISSUE TITLE
 plotAnnoPie from ChIPseeker gives incomplete legends

### ISSUE THREAD

**Issue by ahua217** [YuLab-SMU/ChIPseeker#134]
>Hello! I have some bed files from CUT & RUN analysis by SEACR. Now I use ChIPseeker to plot the chromosome distribution of peaks. This is what I entered:

library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(clusterProfiler)
library(org.Hs.eg.db)
peak <-readPeakFile("/Users/AAData/stringent.bed")
peak

>GRanges object with 23530 ranges and 3 metadata columns:
seqnames ranges strand | V4 V5 V6
| 
[1] chr1 10128-10532 * | 8748.63 43.6341 chr1:10292-10414
[2] chr1 19087-19758 * | 9414.04 32.7256 chr1:19514-19522
[3] chr1 228294-228653 * | 7515.96 32.7256 chr1:228420-228556
[4] chr1 230971-231510 * | 11573.9 43.6341 chr1:231129-231131
[5] chr1 259534-260085 * | 7668.68 32.7256 chr1:259753-259761
... ... ... ... . ... ... ...
[23526] chrY 13869691-13869895 * | 7385.06 65.4511 chrY:13869771-13869844
[23527] chrY 28797432-28798089 * | 7254.15 21.817 chrY:28798040-28798047
[23528] chrY 58992162-58992530 * | 7428.69 54.5426 chrY:58992403-58992415
[23529] chrY 58994709-58995034 * | 9119.52 54.5426 chrY:58994907-58994939
[23530] chrY 59016879-59017391 * | 9948.56 32.7256 chrY:59016905-59017061

plotAnnoPie(peakAnno)

![image](https://user-images.githubusercontent.com/71511628/93612021-078bb700-f99d-11ea-89e6-8732cecf8e11.png)
>The pie plot has incomplete legends. How can I fix them? (btw, the plotAnnoBar has no problem.)
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/chipseeker/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/chipseeker/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `ChIPseeker`

**Comment by MingLi-929** [comment]
I also meet this problem but I try to solve it by adding "ndigit" parameter.
Add parameter-"ndigit" may help you solve this problem,
like `plotAnnoPie(peakAnno,ndigit=1)`.
You may try different ndigits untill it fits your need.
You can have a try to see if it works,thk!

**Comment by MingLi-929** [comment]
but change the ndigit parameter may sacrifice precision (ex 2.22->2.2)!
