### ISSUE TITLE
covplot for GRangesList not working as intended

### ISSUE THREAD

**Issue by MrKevinDC** [YuLab-SMU/ChIPseeker#143]
Hi, I was having trouble running the code included at your answer to the [covplot issue](https://guangchuangyu.github.io/2016/02/covplot-supports-grangeslist/) raised several years ago. When  I source the code:

> chrY dosen't contain signal higher than 1
> New names:
> * chr -> chr...2
> * start -> start...3
> * end -> end...4
> * value -> value...5
> * chr -> chr...6
> * ...
> New names:
> * chr -> chr...2
> * start -> start...3
> * end -> end...4
> * value -> value...5
> * chr -> chr...6
> * ...
> Error: Assigned data `factor(tm$chr, levels = chr.sorted)` must be compatible with existing data.
> x Existing data has 2994 rows.
> x Assigned data has 0 rows.
> ℹ Only vectors of size 1 are recycled.
> Run `rlang::last_error()` to see where the error occurred.
> In addition: Warning message:
> Unknown or uninitialised column: `chr`.

**Comment by GuangchuangYu** [comment]
The issue had been fixed in github version, see also <https://github.com/YuLab-SMU/ChIPseeker/issues/133>.
