### ISSUE TITLE
annotatePeak annoDb error

### ISSUE THREAD

**Issue by igordot** [YuLab-SMU/ChIPseeker#41]
I can run `annotatePeak(peaks, TxDb = txdb)` fine. However, I wanted to add gene names, so I added `annoDb` parameter. That gave me an error.

```
> peak_anno = annotatePeak(peaks, TxDb = txdb, annoDb="org.Mm.eg.db")
>> preparing features information...         2016-09-19 09:32:45 PM 
>> identifying nearest features...       2016-09-19 09:32:45 PM 
>> calculating distance from peak to TSS...  2016-09-19 09:32:48 PM 
>> assigning genomic annotation...       2016-09-19 09:32:48 PM 
>> adding gene annotation...             2016-09-19 09:32:52 PM 
Error in grepl("^\\d+$", , peak.gr$geneId[1]) : 
  argument "x" is missing, with no default
```

I have a custom `TxDb` based on a GTF, but it has a `geneId` column with values like `ENSMUSG00000102851`, so it should be working.

I tried to troubleshoot this myself, but can't find that line anywhere in the ChIPseeker codebase.

**Comment by GuangchuangYu** [comment]
pls install the github version and try again.

**Comment by xpan1** [comment]
How to find annoDb I want, is this available for every species? Thanks

**Comment by GuangchuangYu** [comment]
see the annotationHub package from Bioconductor project.
