### ISSUE TITLE
could the "plotAvgProf" can get the region from TSS to TTS ?

### ISSUE THREAD

**Issue by jailynai** [YuLab-SMU/ChIPseeker#87]
I want to analysis to the situation that protein binding region in TSS to TTS ?
could you tell me where i can set the TTS region
thanks

**Comment by GuangchuangYu** [comment]
currently not supported.

**Comment by GuangchuangYu** [comment]
With <https://github.com/YuLab-SMU/ChIPseeker/pull/156>, now we are able to plot TTS region.

@MingLi-929 pls write a function that is similar to `getPromoters`, for TTS.
